export const images = [
  {
    name: "ball",
    path: "image/ball.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "balloon_blue",
    path: "image/balloon_blue.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "balloon_green",
    path: "image/balloon_green.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "balloon_red",
    path: "image/balloon_red.png",
    element: null,
    isLoaded: false,
  },

  {
    name: "bird_damage",
    path: "image/bird_damage.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "bird_wing_down",
    path: "image/bird_wing_down.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "bird_wing_up",
    path: "image/bird_wing_up.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "construction_sign",
    path: "image/construction_sign.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "heart_full",
    path: "image/heart_full.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "heart_empty",
    path: "image/heart_empty.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "jelly_blue",
    path: "image/jelly_blue.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "jelly_gray",
    path: "image/jelly_gray.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "jelly_gray_2",
    path: "image/jelly_gray_2.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "jelly_green",
    path: "image/jelly_green.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "jelly_pink",
    path: "image/jelly_pink.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "jelly_yellow",
    path: "image/jelly_yellow.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "mailbox",
    path: "image/mailbox.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "scarecrow",
    path: "image/scarecrow.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "sickle",
    path: "image/sickle.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "snowball",
    path: "image/snowball.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "snowball",
    path: "image/snowball.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "snowman",
    path: "image/snowman.png",
    element: null,
    isLoaded: false,
  },
  {
    name: "title",
    path: "image/title.png",
    element: null,
    isLoaded: false,
  },
];
